Tardigrades have about 200 neurons, I doubt this first notebook will even get that far but it is setting up the setting of naming these notebooks in increasing neural complexity of creatures to explain where we are on our own neural development.

In [27]:
print("Hello, Neurons!")

Hello, Neurons!


In [28]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

In [29]:
output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias

print(output)

2.3


In [30]:
inputs.append(2.5)
weights.append(1.0)

In [31]:
def calculate_output(inputs, weights, bias):
    output = 0
    for i in range(len(inputs)):
        output += inputs[i] * weights[i]
    output += bias
    return output


output = calculate_output(inputs, weights, bias)
print(output)

4.8


In [32]:
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [33]:
outputs = [
    # Neuron 1:
    calculate_output(inputs, weights1, bias1),
    # Neuron 2:
    calculate_output(inputs, weights2, bias2),
    # Neuron 3:
    calculate_output(inputs, weights3, bias3),
]

print(outputs)

[4.8, 1.21, 2.385]


In [34]:
weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

In [35]:
def calculate_full_neuron(inputs, weights, bias):
    output_layer = []
    for neuron_weights, neuron_bias in zip(weights, biases):
        output_layer.append(calculate_output(inputs, neuron_weights, neuron_bias))
    return output_layer


outputs = calculate_full_neuron(inputs, weights, biases)
print(outputs)

[4.8, 1.21, 2.385]


# Math Break

In [36]:
a = [1, 2, 3]
b = [2, 3, 4]

In [37]:
dot_product = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
print(dot_product)

20


# And we're back!

In [38]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [39]:
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


In [40]:
def dot_neuron(inputs, weights, bias):
    return np.dot(weights, inputs) + bias

In [41]:
weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [42]:
layer_outputs = dot_neuron(inputs, weights, biases)
print(layer_outputs)

[4.8   1.21  2.385]


# Math Break

In [43]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

In [44]:
a_mat = np.array([a])
b_mat = np.array([b]).T

print(a_mat)
print(b_mat)

[[1 2 3]]
[[2]
 [3]
 [4]]


In [45]:
dot_product = np.dot(a_mat, b_mat)

print(dot_product)

[[20]]


# And we're back!

In [46]:
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

In [47]:
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
